name: "dbt_postgresql_project"
version: "1.0.0"
config-version: 2

profile: "dbt_postgresql_project"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_postgresql_project:
    example:
      +materialized: table
